In [13]:
from sklearn.datasets import load_iris

In [14]:
dt=load_iris()

In [15]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [16]:
import pandas as pd
import numpy as np

In [17]:
df=pd.DataFrame(dt.data,columns=dt.feature_names)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [19]:
df['target']=dt.target

In [20]:
df.tail(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
140                6.7               3.1                5.6               2.4   
141                6.9               3.1                5.1               2.3   
142                5.8               2.7                5.1               1.9   
143                6.8               3.2                5.9               2.3   
144                6.7               3.3                5.7               2.5   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
140       2  
141       2  
142       2  
143       2  
144       2  
145       2  
146       2  
147       2  
148       2  
149       2

In [21]:
df['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [22]:
df_copy=df[df['target']!=2]

In [23]:
x=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [25]:
from sklearn.linear_model import LogisticRegression
classfier=LogisticRegression()
classfier

LogisticRegression()

In [26]:
classfier.fit(x_train,y_train)

LogisticRegression()

In [27]:
y_pred=classfier.predict(x_test)

In [28]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [30]:
from sklearn.model_selection import KFold,cross_val_score
cv=KFold(n_splits=5)


In [31]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [32]:
cross_val_score(classfier,x_train,y_train,cv=cv,scoring='accuracy')

array([1., 1., 1., 1., 1.])

In [33]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

x,y=make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [34]:
x

array([[ 1.89149379, -0.39847585,  1.63856893, ...,  0.58810926,
        -0.02542177, -0.52835426],
       [ 1.86913773, -0.56336215,  2.03411807, ..., -0.55633   ,
        -0.27340013,  0.72129251],
       [ 1.95259701, -2.83144572,  0.19055535, ..., -0.60957741,
        -2.07750191, -1.75469982],
       ...,
       [ 1.98033054,  1.37228804,  1.67376262, ...,  2.75687956,
        -0.20719842,  0.39299534],
       [-1.54305631, -0.27530218,  0.38744703, ...,  0.72769107,
         0.51983329, -1.92306657],
       [ 1.17970389, -3.3812155 , -0.1498426 , ...,  1.24640268,
        -4.00356845, -3.01027048]])

In [35]:
y

array([1, 0, 1, 2, 0, 2, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0, 1, 0, 2, 0,
       2, 2, 0, 0, 2, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 1, 2, 2, 2, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 1, 2, 1,
       1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 1, 2, 2, 2,
       0, 1, 0, 2, 1, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 2, 2,
       1, 2, 0, 2, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 0, 0, 1,
       0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 2, 0, 1, 2, 0, 2, 1, 2, 0, 0, 1,
       0, 0, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       2, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 1, 1, 0,
       1, 1, 1, 1, 2, 1, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 0, 2, 2, 2, 0, 2,
       0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1, 2, 0, 2, 2,
       1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2,
       1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1,
       1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 0, 0, 2, 1, 1,

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [37]:
from sklearn.linear_model import LogisticRegression
classfier1=LogisticRegression()
classfier1

LogisticRegression()

In [38]:
classfier1.fit(x_train,y_train)

LogisticRegression()

In [39]:
y_pred_1=classfier1.predict(x_test)

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred_1))
print(accuracy_score(y_test,y_pred_1))
print(classification_report(y_test,y_pred_1))

[[57 15  3]
 [13 39 12]
 [16  6 39]]
0.675
              precision    recall  f1-score   support

           0       0.66      0.76      0.71        75
           1       0.65      0.61      0.63        64
           2       0.72      0.64      0.68        61

    accuracy                           0.68       200
   macro avg       0.68      0.67      0.67       200
weighted avg       0.68      0.68      0.67       200



In [41]:
cv1=KFold(n_splits=5)

In [42]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [43]:
score=cross_val_score(classfier,x_train,y_train,cv=cv1)
score

array([0.74375, 0.70625, 0.65   , 0.65   , 0.68125])

In [44]:
np.mean(score)

0.68625

In [45]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
import warnings
warnings.filterwarnings('ignore')



In [46]:
parameters={'penalty':('l1','l2','elasticnet'),'C':[1,2,3,4,5,6,7,8,9,10]}


In [47]:
clf=GridSearchCV(classfier1,param_grid=parameters,cv=5)

In [48]:
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [49]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [50]:
classfier1=LogisticRegression(C=1,penalty='l2')

In [51]:
classfier1.fit(x_train,y_train)

LogisticRegression(C=1)

In [52]:
y_pred_1=classfier1.predict(x_test)

In [53]:
print(confusion_matrix(y_test,y_pred_1))
print(accuracy_score(y_test,y_pred_1))
print(classification_report(y_test,y_pred_1))

[[57 15  3]
 [13 39 12]
 [16  6 39]]
0.675
              precision    recall  f1-score   support

           0       0.66      0.76      0.71        75
           1       0.65      0.61      0.63        64
           2       0.72      0.64      0.68        61

    accuracy                           0.68       200
   macro avg       0.68      0.67      0.67       200
weighted avg       0.68      0.68      0.67       200



In [54]:
clf.best_score_

0.6875

In [55]:
rand=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5,n_iter=20)

In [56]:
rand

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [57]:
rand.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [58]:
rand.best_params_

{'penalty': 'l2', 'C': 7}

# multiclass classification

In [59]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

x,y=make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [60]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(multi_class='ovr',solver='lbfgs')

In [61]:
model

LogisticRegression(multi_class='ovr')

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [63]:
model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [64]:
model.predict(x_test)

array([1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0,
       2, 1, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 2, 0, 1,
       2, 1, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1,
       0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 0,
       2, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 0,
       2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0])

In [65]:
y_test

array([1, 1, 2, 2, 1, 1, 2, 2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0,
       2, 1, 1, 1, 0, 0, 2, 2, 2, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 2, 2, 0, 0, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1,
       2, 0, 2, 0, 2, 2, 2, 0, 1, 2, 2, 2, 2, 2, 0, 1, 0, 0, 2, 0, 2, 1,
       0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 2, 0, 2, 2,
       2, 1, 1, 2, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2,
       2, 2, 1, 2, 2, 2, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 1, 2,
       2, 0, 0, 2, 2, 1, 2, 2, 1, 1, 0, 0, 2, 1, 2, 2, 0, 1, 1, 2, 1, 0,
       1, 1, 0, 2, 2, 2, 1, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 2,
       1, 2])

In [66]:
model.predict_proba(x_test)

array([[9.10641007e-02, 5.88918814e-01, 3.20017086e-01],
       [7.74913438e-02, 8.83935792e-01, 3.85728639e-02],
       [6.84424719e-01, 2.03486076e-01, 1.12089205e-01],
       [1.43078246e-02, 9.01463818e-02, 8.95545794e-01],
       [6.87563505e-02, 8.36639008e-01, 9.46046415e-02],
       [1.08997130e-01, 3.07635489e-01, 5.83367380e-01],
       [3.78574343e-01, 2.08257319e-01, 4.13168338e-01],
       [3.14075303e-01, 1.75938154e-01, 5.09986543e-01],
       [5.14661374e-01, 1.90320746e-01, 2.95017880e-01],
       [5.97855686e-01, 3.02391035e-01, 9.97532791e-02],
       [4.20049273e-02, 3.31576489e-01, 6.26418584e-01],
       [4.86732760e-01, 1.04800924e-01, 4.08466316e-01],
       [8.01128811e-01, 3.37464192e-02, 1.65124770e-01],
       [8.98155592e-02, 6.97988466e-01, 2.12195975e-01],
       [7.29031504e-02, 8.39118736e-01, 8.79781132e-02],
       [5.10593601e-01, 2.09236547e-01, 2.80169852e-01],
       [1.24309393e-01, 7.90830108e-01, 8.48604992e-02],
       [3.42809146e-03, 3.71695

In [67]:
y_pred_12=model.predict(x_test)

In [68]:
print(confusion_matrix(y_test,y_pred_12))
print(accuracy_score(y_test,y_pred_12))
print(classification_report(y_test,y_pred_12))

[[56 16  3]
 [10 41 13]
 [17  6 38]]
0.675
              precision    recall  f1-score   support

           0       0.67      0.75      0.71        75
           1       0.65      0.64      0.65        64
           2       0.70      0.62      0.66        61

    accuracy                           0.68       200
   macro avg       0.68      0.67      0.67       200
weighted avg       0.68      0.68      0.67       200

